### ISSUE TITLE
If a second RTMP stream connects we crash

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#13]
```
goroutine 19555 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000b0000, 0xc00013dad0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/gabek/src/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x335
github.com/sirupsen/logrus.(*Entry).Log(0xc0001a6460, 0xc000000000, 0xc000c65bf0, 0x1, 0x1)
        /home/gabek/src/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xeb
github.com/sirupsen/logrus.(*Logger).Log(0xc0000b0000, 0xc000000000, 0xc000c65bf0, 0x1, 0x1)
        /home/gabek/src/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:193 +0x7d
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /home/gabek/src/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:234
github.com/sirupsen/logrus.Panic(...)
        /home/gabek/src/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/exported.go:129
main.verifyError(...)
        /home/gabek/src/video-stream/utils.go:38
main.startFfmpeg(0x0, 0xc00049a260, 0xf, 0xc00049a0d0, 0xb, 0xc00049a0f8, 0x3, 0x4, 0xc00049a190, 0x6, ...)
        /home/gabek/src/video-stream/ffmpeg.go:178 +0x1242
created by main.(*Handler).OnPublish
        /home/gabek/src/video-stream/handler.go:69 +0x3b0
exit status 2
```

Should both fix the crash and reject concurrent incoming RTMP connections?

**Comment by graywolf336** [comment]
Yeah, I would say reject the incoming stream if there is already one active.
