### ISSUE TITLE
Handle S3 error

### ISSUE THREAD

**Issue by gabek** [gabek/owncast#3]
It's a purposeful panic, so look into it and handle it.

```
panic: RequestError: send request failed
caused by: Put "https://s3.us-west-2.amazonaws.com/gabevideo/hls/0/stream-20200617-1592382043.ts": write tcp 74.207.245.84:57926->52.218.222.8:443: use of closed network connection

goroutine 81672 [running]:
main.(*S3Storage).Save(0xc0000e2000, 0xc0005f4000, 0x23, 0x0, 0x0)
        /home/gabek/src/video-stream/s3Storage.go:58 +0x38e
main.monitorVideoContent.func1.1(0x22a6300, 0xc0000e2000, 0xc0000b4900, 0xc000195180, 0xc00026a1e0)
        /home/gabek/src/video-stream/playlistMonitor.go:105 +0xb1
created by main.monitorVideoContent.func1
        /home/gabek/src/video-stream/playlistMonitor.go:104 +0x470
exit status 2
```

**Comment by gabek** [comment]
This is no longer fatal and there's a hard-coded, stupid simple retry (with no backoff.  Should make this a real retry mechanism at some point.)
