### ISSUE TITLE
webroot/thumbnail.png: No such file or directory

### ISSUE THREAD

**Issue by graywolf336** [gabek/owncast#7]
When running for the first time, I run into the following error:

```
Enabling passthrough video
/usr/local/bin/ffmpeg -hide_banner -i doc/logo.png -i webroot/thumbnail.png -filter_complex "[0:v]scale=2640:2360[bg];[bg][1:v]overlay=200:250:enable='between(t,0,3)'"  -f hls -hls_time 4 -hls_playlist_type event -master_pl_name stream.m3u8 -strftime 1 -use_localtime 1 -hls_flags temp_file -tune zerolatency -g 50  -keyint_min 50 -framerate 25 -preset superfast -sc_threshold 0 -profile:v main -pix_fmt yuv420p -var_stream_map "v:0" -hls_segment_filename webroot/hls/%v/offline-%s.ts webroot/hls/%v/stream.m3u8
exit status 1
PANI[0000] exit status 1                                
panic: (*logrus.Entry) (0x52af2a0,0xc000422070)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000142000, 0xc0004c0120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/bradleyhilton/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x335
github.com/sirupsen/logrus.(*Entry).Log(0xc000422000, 0xc000000000, 0xc00063fa10, 0x1, 0x1)
        /Users/bradleyhilton/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xeb
github.com/sirupsen/logrus.(*Logger).Log(0xc000142000, 0xc000000000, 0xc00063fa10, 0x1, 0x1)
        /Users/bradleyhilton/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:193 +0x7d
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /Users/bradleyhilton/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:234
github.com/sirupsen/logrus.Panic(...)
        /Users/bradleyhilton/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/exported.go:129
main.verifyError(...)
        /Users/bradleyhilton/go/src/github.com/graywolf336/owncast/utils.go:38
main.showStreamOfflineState(0x0, 0xc0000471d0, 0xf, 0xc000047020, 0xb, 0xc000047040, 0x3, 0x4, 0xc0000470f0, 0x6, ...)
        /Users/bradleyhilton/go/src/github.com/graywolf336/owncast/ffmpeg.go:88 +0xd85
main.createInitialOfflineState()
        /Users/bradleyhilton/go/src/github.com/graywolf336/owncast/utils.go:81 +0x54
main.main()
        /Users/bradleyhilton/go/src/github.com/graywolf336/owncast/main.go:47 +0x1e9
exit status 2
```

And when I run the `ffmpeg` command, it gives me: `webroot/thumbnail.png: No such file or directory`

Obviously, I can place a file there but figured I would open this issue just to let you know and maybe a file can be placed there for people wanting to download it and just try it out.

**Comment by gabek** [comment]
Oh nice, good catch!  Fixed!
